using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Map : MonoBehaviour {

	public GameObject BorderHex1;
    public GameObject BorderHex2;
    public GameObject BorderHex3;
    public GameObject BorderHex4;
    public GameObject BorderHex5;
    public GameObject BorderHex6;
    public GameObject[] hexagonPositions;

	int width  = StaticVariables.gridWidth;
	int height = StaticVariables.gridHeight;

	int iCoord;
	int radiusSize;
	float baseHeight = -0.45f;

	List<float> xNodeList = new List<float>();
	List<float> yNodeList = new List<float>();

	void Awake () {

		GenerateMapData ();
		GenerateMapVisuals ();

    }

	void GenerateMapData(){

		// Placeholder on the map
		for (int x = 0; x < width; x++)
		{
			for (int y = 0; y < height; y++)
			{

				float xPos = x * StaticVariables.xOffset;
				float yPos = y * StaticVariables.yOffset;

				// if we are on a odd row y axis, then offset x by xOffset
				if (y != 0)
				{
					xPos += ((StaticVariables.xOffset / 2f) * y);
				}

				//GameObject hex_go = (GameObject)Instantiate (NodePrefab, new Vector3 (xPos, -1f, yPos), Quaternion.identity);

				// Name each hexagon something sensible and display
				// hex_go.name = "Hex_" + x + "_" + y;
				// Debug.Log (hex_go.name);

				// Create all the hexagons under a parent in the heirarchy
				//hex_go.transform.SetParent(this.transform);
		
				xNodeList.Add (xPos);
				yNodeList.Add (yPos);
		
				//hex_go.isStatic = true; // ????

				//Debug.Log (xNodeList [x] + " : " + yNodeList [y]);
				//Debug.Log("Hex Name: " + hex_go.name);

			}
		} 
	}

	void GenerateMapVisuals(){

		int centreHexCoordArray = xNodeList.Count / 2; // centre hexagons coordinates are in the array at this extent

		// centre
		iCoord = centreHexCoordArray; 
		Instantiate (hexagonPositions[0], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		// radius 1
		iCoord = centreHexCoordArray - 1; 
		Instantiate (hexagonPositions[1], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height; 
		Instantiate (hexagonPositions[2], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height + 1; 
		Instantiate (hexagonPositions[3], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 1; 
		Instantiate (hexagonPositions[4], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height; 
		Instantiate (hexagonPositions[5], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height - 1; 
		Instantiate (hexagonPositions[6], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		// radius 2
		iCoord = centreHexCoordArray - 2; 
		Instantiate (hexagonPositions[7], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 1; 
		Instantiate (hexagonPositions[8], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height); 
		Instantiate (hexagonPositions[9], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 1; 
		Instantiate (hexagonPositions[10], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 2; 
		Instantiate (hexagonPositions[11], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height + 2; 
		Instantiate (hexagonPositions[12], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 2; 
		Instantiate (hexagonPositions[13], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 1; 
		Instantiate (hexagonPositions[14], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height); 
		Instantiate (hexagonPositions[15], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 1; 
		Instantiate (hexagonPositions[16], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 2; 
		Instantiate (hexagonPositions[17], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height - 2; 
		Instantiate (hexagonPositions[18], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		//radius 3
		iCoord = centreHexCoordArray - 3; 
		Instantiate (hexagonPositions[19], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 2; 
		Instantiate (hexagonPositions[20], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 1; 
		Instantiate (hexagonPositions[21], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height); 
		Instantiate (hexagonPositions[22], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 1; 
		Instantiate (hexagonPositions[23], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 2; 
		Instantiate (hexagonPositions[24], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 3; 
		Instantiate (hexagonPositions[25], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 3; 
		Instantiate (hexagonPositions[26], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height + 3; 
		Instantiate (hexagonPositions[27], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 3; 
		Instantiate (hexagonPositions[28], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 2; 
		Instantiate (hexagonPositions[29], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 1; 
		Instantiate (hexagonPositions[30], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height); 
		Instantiate (hexagonPositions[31], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 1; 
		Instantiate (hexagonPositions[32], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 2; 
		Instantiate (hexagonPositions[33], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 3; 
		Instantiate (hexagonPositions[34], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
        iCoord = centreHexCoordArray + (2 * height) - 3;
        Instantiate(hexagonPositions[35], new Vector3(xNodeList[iCoord], baseHeight, yNodeList[iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height - 3; 
		Instantiate (hexagonPositions[36], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		

		//radius 4
		iCoord = centreHexCoordArray - 4; 
		Instantiate (hexagonPositions[37], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 3; 
		Instantiate (hexagonPositions[38], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 2; 
		Instantiate (hexagonPositions[39], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 1; 
		Instantiate (hexagonPositions[40], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height); 
		Instantiate (hexagonPositions[41], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 1; 
		Instantiate (hexagonPositions[42], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 2; 
		Instantiate (hexagonPositions[43], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 3; 
		Instantiate (hexagonPositions[44], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 4; 
		Instantiate (hexagonPositions[45], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 4; 
		Instantiate (hexagonPositions[46], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 4; 
		Instantiate (hexagonPositions[47], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 4; 
		Instantiate (hexagonPositions[48], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 4; 
		Instantiate (hexagonPositions[49], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 3; 
		Instantiate (hexagonPositions[50], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 2; 
		Instantiate (hexagonPositions[51], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 1; 
		Instantiate (hexagonPositions[52], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height); 
		Instantiate (hexagonPositions[53], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 1; 
		Instantiate (hexagonPositions[54], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 2; 
		Instantiate (hexagonPositions[55], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 3; 
		Instantiate (hexagonPositions[56], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 4; 
		Instantiate (hexagonPositions[57], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 4; 
		Instantiate (hexagonPositions[58], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 4; 
		Instantiate (hexagonPositions[59], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height - 4; 
		Instantiate (hexagonPositions[60], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity); 

		//radius 5
		iCoord = centreHexCoordArray - 5; 
		Instantiate (hexagonPositions[61], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 4; 
		Instantiate (hexagonPositions[62], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 3; 
		Instantiate (hexagonPositions[63], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 2; 
		Instantiate (hexagonPositions[64], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 1; 
		Instantiate (hexagonPositions[65], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height); 
		Instantiate (hexagonPositions[66], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 1; 
		Instantiate (hexagonPositions[67], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 2; 
		Instantiate (hexagonPositions[68], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 3; 
		Instantiate (hexagonPositions[69], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 4; 
		Instantiate (hexagonPositions[70], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 5; 
		Instantiate (hexagonPositions[71], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 5; 
		Instantiate (hexagonPositions[72], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 5; 
		Instantiate (hexagonPositions[73], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 5; 
		Instantiate (hexagonPositions[74], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 5; 
		Instantiate (hexagonPositions[75], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 5; 
		Instantiate (hexagonPositions[76], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 4; 
		Instantiate (hexagonPositions[77], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 3; 
		Instantiate (hexagonPositions[78], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 2; 
		Instantiate (hexagonPositions[79], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + 1; 
		Instantiate (hexagonPositions[80], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height); 
		Instantiate (hexagonPositions[81], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
	    iCoord = centreHexCoordArray + (5*height) - 1; 
		Instantiate (hexagonPositions[82], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 2; 
		Instantiate (hexagonPositions[83], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 3; 
		Instantiate (hexagonPositions[84], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 4; 
		Instantiate (hexagonPositions[85], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 5; 
		Instantiate (hexagonPositions[86], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 5; 
		Instantiate (hexagonPositions[87], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 5; 
		Instantiate (hexagonPositions[88], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 5; 
		Instantiate (hexagonPositions[89], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - 5; 
		Instantiate (hexagonPositions[90], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		//radius 6 
		iCoord = centreHexCoordArray - 6; 
		Instantiate (hexagonPositions[91], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 5; 
		Instantiate (hexagonPositions[92], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 4; 
		Instantiate (hexagonPositions[93], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 3; 
		Instantiate (hexagonPositions[94], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 2; 
		Instantiate (hexagonPositions[95], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) - 1; 
		Instantiate (hexagonPositions[96], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height); 
		Instantiate (hexagonPositions[97], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 1; 
		Instantiate (hexagonPositions[98], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 2; 
		Instantiate (hexagonPositions[99], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 3; 
		Instantiate (hexagonPositions[100], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 4; 
		Instantiate (hexagonPositions[101], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 5; 
		Instantiate (hexagonPositions[102], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 6; 
		Instantiate (hexagonPositions[103], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 6; 
		Instantiate (hexagonPositions[104], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 6; 
		Instantiate (hexagonPositions[105], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 6; 
		Instantiate (hexagonPositions[106], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 6; 
		Instantiate (hexagonPositions[107], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 6; 
		Instantiate (hexagonPositions[108], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 6; 
		Instantiate (hexagonPositions[109], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 5; 
		Instantiate (hexagonPositions[110], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 4; 
		Instantiate (hexagonPositions[111], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 3; 
		Instantiate (hexagonPositions[112], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + 2; 
		Instantiate (hexagonPositions[113], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) + 1; 
		Instantiate (hexagonPositions[114], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height); 
		Instantiate (hexagonPositions[115], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 1; 
		Instantiate (hexagonPositions[116], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 2; 
		Instantiate (hexagonPositions[117], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 3; 
		Instantiate (hexagonPositions[118], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 4; 
		Instantiate (hexagonPositions[119], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 5; 
		Instantiate (hexagonPositions[120], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 6; 
		Instantiate (hexagonPositions[121], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 6; 
		Instantiate (hexagonPositions[122], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 6; 
		Instantiate (hexagonPositions[123], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 6; 
		Instantiate (hexagonPositions[124], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 6; 
		Instantiate (hexagonPositions[125], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - 6; 
		Instantiate (hexagonPositions[126], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		//radius 7
		iCoord = centreHexCoordArray - 7; 
		Instantiate (hexagonPositions[127], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 6; 
		Instantiate (hexagonPositions[128], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 5; 
		Instantiate (hexagonPositions[129], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 4; 
		Instantiate (hexagonPositions[130], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 3; 
		Instantiate (hexagonPositions[131], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) - 2; 
		Instantiate (hexagonPositions[132], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) - 1; 
		Instantiate (hexagonPositions[133], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height); 
		Instantiate (hexagonPositions[134], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 1; 
		Instantiate (hexagonPositions[135], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 2; 
		Instantiate (hexagonPositions[136], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 3; 
		Instantiate (hexagonPositions[137], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 4; 
		Instantiate (hexagonPositions[138], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 5; 
		Instantiate (hexagonPositions[139], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 6; 
		Instantiate (hexagonPositions[140], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 7; 
		Instantiate (hexagonPositions[141], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 7; 
		Instantiate (hexagonPositions[142], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 7; 
		Instantiate (hexagonPositions[143], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 7; 
		Instantiate (hexagonPositions[144], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 7; 
		Instantiate (hexagonPositions[145], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 7; 
		Instantiate (hexagonPositions[146], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 7; 
		Instantiate (hexagonPositions[147], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 7; 
		Instantiate (hexagonPositions[148], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 6; 
		Instantiate (hexagonPositions[149], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 5; 
		Instantiate (hexagonPositions[150], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 4; 
		Instantiate (hexagonPositions[151], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + 3; 
		Instantiate (hexagonPositions[152], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) + 2; 
		Instantiate (hexagonPositions[153], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) + 1; 
		Instantiate (hexagonPositions[154], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height); 
		Instantiate (hexagonPositions[155], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 1; 
		Instantiate (hexagonPositions[156], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 2; 
		Instantiate (hexagonPositions[157], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 3; 
		Instantiate (hexagonPositions[158], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 4; 
		Instantiate (hexagonPositions[159], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 5; 
		Instantiate (hexagonPositions[160], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 6; 
		Instantiate (hexagonPositions[161], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 7; 
		Instantiate (hexagonPositions[162], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 7; 
		Instantiate (hexagonPositions[163], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 7; 
		Instantiate (hexagonPositions[164], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 7; 
		Instantiate (hexagonPositions[165], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 7; 
		Instantiate (hexagonPositions[166], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 7; 
		Instantiate (hexagonPositions[167], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - 7; 
		Instantiate (hexagonPositions[168], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		//radius 8
		iCoord = centreHexCoordArray - 8; 
		Instantiate (hexagonPositions[169], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 7; 
		Instantiate (hexagonPositions[170], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 6; 
		Instantiate (hexagonPositions[171], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 5; 
		Instantiate (hexagonPositions[172], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 4; 
		Instantiate (hexagonPositions[173], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) - 3; 
		Instantiate (hexagonPositions[174], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) - 2; 
		Instantiate (hexagonPositions[175], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) - 1; 
		Instantiate (hexagonPositions[176], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height); 
		Instantiate (hexagonPositions[177], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 1; 
		Instantiate (hexagonPositions[178], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 2; 
		Instantiate (hexagonPositions[179], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 3; 
		Instantiate (hexagonPositions[180], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 4; 
		Instantiate (hexagonPositions[181], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 5; 
		Instantiate (hexagonPositions[182], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 6; 
		Instantiate (hexagonPositions[183], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 7; 
		Instantiate (hexagonPositions[184], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 8; 
		Instantiate (hexagonPositions[185], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 8; 
		Instantiate (hexagonPositions[186], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 8; 
		Instantiate (hexagonPositions[187], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 8; 
		Instantiate (hexagonPositions[188], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 8; 
		Instantiate (hexagonPositions[189], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 8; 
		Instantiate (hexagonPositions[190], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 8; 
		Instantiate (hexagonPositions[191], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 8; 
		Instantiate (hexagonPositions[192], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 8; 
		Instantiate (hexagonPositions[193], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 7; 
		Instantiate (hexagonPositions[194], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 6; 
		Instantiate (hexagonPositions[195], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 5; 
		Instantiate (hexagonPositions[196], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + 4; 
		Instantiate (hexagonPositions[197], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) + 3; 
		Instantiate (hexagonPositions[198], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) + 2; 
		Instantiate (hexagonPositions[199], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) + 1; 
		Instantiate (hexagonPositions[200], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height); 
		Instantiate (hexagonPositions[201], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 1; 
		Instantiate (hexagonPositions[202], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 2; 
		Instantiate (hexagonPositions[203], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 3; 
		Instantiate (hexagonPositions[204], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 4; 
		Instantiate (hexagonPositions[205], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 5; 
		Instantiate (hexagonPositions[206], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 6; 
		Instantiate (hexagonPositions[207], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 7; 
		Instantiate (hexagonPositions[208], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 8; 
		Instantiate (hexagonPositions[209], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 8; 
		Instantiate (hexagonPositions[210], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 8; 
		Instantiate (hexagonPositions[211], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 8; 
		Instantiate (hexagonPositions[212], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 8; 
		Instantiate (hexagonPositions[213], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 8; 
		Instantiate (hexagonPositions[214], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 8; 
		Instantiate (hexagonPositions[215], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - 8; 
		Instantiate (hexagonPositions[216], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		//radius 9
		iCoord = centreHexCoordArray - 9; 
		Instantiate (hexagonPositions[217], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 8; 
		Instantiate (hexagonPositions[218], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 7; 
		Instantiate (hexagonPositions[219], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 6; 
		Instantiate (hexagonPositions[220], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 5; 
		Instantiate (hexagonPositions[221], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) - 4; 
		Instantiate (hexagonPositions[222], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) - 3; 
		Instantiate (hexagonPositions[223], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) - 2; 
		Instantiate (hexagonPositions[224], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) - 1; 
		Instantiate (hexagonPositions[225], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height); 
		Instantiate (hexagonPositions[226], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 1; 
		Instantiate (hexagonPositions[227], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 2; 
		Instantiate (hexagonPositions[228], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 3; 
		Instantiate (hexagonPositions[229], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 4; 
		Instantiate (hexagonPositions[230], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 5; 
		Instantiate (hexagonPositions[231], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 6; 
		Instantiate (hexagonPositions[232], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 7; 
		Instantiate (hexagonPositions[233], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 8; 
		Instantiate (hexagonPositions[234], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 9; 
		Instantiate (hexagonPositions[235], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 9; 
		Instantiate (hexagonPositions[236], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 9; 
		Instantiate (hexagonPositions[237], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 9; 
		Instantiate (hexagonPositions[238], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 9; 
		Instantiate (hexagonPositions[239], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 9; 
		Instantiate (hexagonPositions[240], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 9; 
		Instantiate (hexagonPositions[241], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 9; 
		Instantiate (hexagonPositions[242], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 9; 
		Instantiate (hexagonPositions[243], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 9; 
		Instantiate (hexagonPositions[244], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 8; 
		Instantiate (hexagonPositions[245], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 7; 
		Instantiate (hexagonPositions[246], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 6; 
		Instantiate (hexagonPositions[247], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + 5; 
		Instantiate (hexagonPositions[248], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) + 4; 
		Instantiate (hexagonPositions[249], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) + 3; 
		Instantiate (hexagonPositions[250], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) + 2; 
		Instantiate (hexagonPositions[251], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) + 1; 
		Instantiate (hexagonPositions[252], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height); 
		Instantiate (hexagonPositions[253], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 1; 
		Instantiate (hexagonPositions[254], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 2; 
		Instantiate (hexagonPositions[255], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 3; 
		Instantiate (hexagonPositions[256], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 4; 
		Instantiate (hexagonPositions[257], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 5; 
		Instantiate (hexagonPositions[258], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 6; 
		Instantiate (hexagonPositions[259], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 7; 
		Instantiate (hexagonPositions[260], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 8; 
		Instantiate (hexagonPositions[261], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 9; 
		Instantiate (hexagonPositions[262], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 9; 
		Instantiate (hexagonPositions[263], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 9; 
		Instantiate (hexagonPositions[264], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 9; 
		Instantiate (hexagonPositions[265], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 9; 
		Instantiate (hexagonPositions[266], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 9; 
		Instantiate (hexagonPositions[267], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 9; 
		Instantiate (hexagonPositions[268], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 9; 
		Instantiate (hexagonPositions[269], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - 9; 
		Instantiate (hexagonPositions[270], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		//radius 10
		iCoord = centreHexCoordArray - 10; 
		Instantiate (hexagonPositions[271], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 9; 
		Instantiate (hexagonPositions[272], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 8; 
		Instantiate (hexagonPositions[273], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 7; 
		Instantiate (hexagonPositions[274], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 6; 
		Instantiate (hexagonPositions[275], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) - 5; 
		Instantiate (hexagonPositions[276], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) - 4; 
		Instantiate (hexagonPositions[277], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) - 3; 
		Instantiate (hexagonPositions[278], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) - 2; 
		Instantiate (hexagonPositions[279], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) - 1; 
		Instantiate (hexagonPositions[280], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height); 
		Instantiate (hexagonPositions[281], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 1; 
		Instantiate (hexagonPositions[282], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 2; 
		Instantiate (hexagonPositions[283], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 3; 
		Instantiate (hexagonPositions[284], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 4; 
		Instantiate (hexagonPositions[285], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 5; 
		Instantiate (hexagonPositions[286], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 6; 
		Instantiate (hexagonPositions[287], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 7; 
		Instantiate (hexagonPositions[288], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 8; 
		Instantiate (hexagonPositions[289], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 9; 
		Instantiate (hexagonPositions[290], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + 10; 
		Instantiate (hexagonPositions[291], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + 10; 
		Instantiate (hexagonPositions[292], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + 10; 
		Instantiate (hexagonPositions[293], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + 10; 
		Instantiate (hexagonPositions[294], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + 10; 
		Instantiate (hexagonPositions[295], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + 10; 
		Instantiate (hexagonPositions[296], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + 10; 
		Instantiate (hexagonPositions[297], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + 10; 
		Instantiate (hexagonPositions[298], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + 10; 
		Instantiate (hexagonPositions[299], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + 10; 
		Instantiate (hexagonPositions[300], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + 10; 
		Instantiate (hexagonPositions[301], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + 9; 
		Instantiate (hexagonPositions[302], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + 8; 
		Instantiate (hexagonPositions[303], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + 7; 
		Instantiate (hexagonPositions[304], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + 6; 
		Instantiate (hexagonPositions[305], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) + 5; 
		Instantiate (hexagonPositions[306], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) + 4; 
		Instantiate (hexagonPositions[307], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) + 3; 
		Instantiate (hexagonPositions[308], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) + 2; 
		Instantiate (hexagonPositions[309], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) + 1; 
		Instantiate (hexagonPositions[310], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height); 
		Instantiate (hexagonPositions[311], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 1; 
		Instantiate (hexagonPositions[312], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 2; 
		Instantiate (hexagonPositions[313], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 3; 
		Instantiate (hexagonPositions[314], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 4; 
		Instantiate (hexagonPositions[315], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 5; 
		Instantiate (hexagonPositions[316], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 6; 
		Instantiate (hexagonPositions[317], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 7; 
		Instantiate (hexagonPositions[318], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 8; 
		Instantiate (hexagonPositions[319], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 9; 
		Instantiate (hexagonPositions[320], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - 10; 
		Instantiate (hexagonPositions[321], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - 10; 
		Instantiate (hexagonPositions[322], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - 10; 
		Instantiate (hexagonPositions[323], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - 10; 
		Instantiate (hexagonPositions[324], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - 10; 
		Instantiate (hexagonPositions[325], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - 10; 
		Instantiate (hexagonPositions[326], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - 10; 
		Instantiate (hexagonPositions[327], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - 10; 
		Instantiate (hexagonPositions[328], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - 10; 
		Instantiate (hexagonPositions[329], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - 10; 
		Instantiate (hexagonPositions[330], new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);

		// Border radius 11
		radiusSize = 11;
		iCoord = centreHexCoordArray - radiusSize; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - height - 10; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) - 9; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);	
		iCoord = centreHexCoordArray - (3*height) - 8; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) - 7; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) - 6; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) - 5; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) - 4; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) - 3; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) - 2; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) - 1; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height); 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 1; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 2; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 3; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 4; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 5; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 6; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 7; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 8; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 9; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 10; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (radiusSize*height) + 11; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (10*height) + radiusSize; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (9*height) + radiusSize; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (8*height) + radiusSize; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (7*height) + radiusSize; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (6*height) + radiusSize; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (5*height) + radiusSize; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (4*height) + radiusSize; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (3*height) + radiusSize; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (2*height) + radiusSize; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray - (height) + radiusSize; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + radiusSize; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + height + radiusSize - 1; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) + radiusSize - 2; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) + radiusSize - 3; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) + radiusSize - 4; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) + radiusSize - 5; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) + radiusSize - 6; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) + radiusSize - 7; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) + radiusSize - 8; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) + radiusSize - 9; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) + radiusSize - 10; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height); 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 1; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 2; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 3; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 4; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 5; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 6; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 7; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 8; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 9; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 10; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (radiusSize*height) - 11; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (10*height) - radiusSize; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (9*height) - radiusSize; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (8*height) - radiusSize; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (7*height) - radiusSize; 
		Instantiate (BorderHex5, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (6*height) - radiusSize; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (5*height) - radiusSize; 
		Instantiate (BorderHex1, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (4*height) - radiusSize; 
		Instantiate (BorderHex3, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (3*height) - radiusSize; 
		Instantiate (BorderHex4, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (2*height) - radiusSize; 
		Instantiate (BorderHex6, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
		iCoord = centreHexCoordArray + (height) - radiusSize; 
		Instantiate (BorderHex2, new Vector3 (xNodeList [iCoord], baseHeight, yNodeList [iCoord]), Quaternion.identity);
	}
}
